# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39863119da01ec449ba0b446321eec293036610cdebfd1edd82f64e35c82eae025e7055d05eb533ce7adb7e294999f56b28672ea73f5157ea911808c0722687b

test:
  secret_key_base: ed2d28eba808d3247b6f17fa464e60ce2f243ef57dc073a258e91b5d3fd2e17dc86c131756d9f4b500f15f74f65a283bd36f861b665ddbe0db77b07603674976

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
